/*
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.auth;

import org.openapitools.client.ApiException;

import java.net.http.HttpClient;
import java.net.http.HttpRequest;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0-SNAPSHOT")
public interface Authentication {
    /**
     * Apply authentication settings request and cookies.
     *
     * @param requestBuilder Reuest builder to apply authentication settings to
     * @param httpClient HttpClient to get the cookie manager from
     */
    void applyToParams(HttpRequest.Builder requestBuilder, HttpClient httpClient) throws ApiException;

}
